###########################
#       DoorsReloaded     #
###########################

# written by mfnalex / JEFF Media GbR
# Community continuation of DoorsReloaded is maintained by Semarina organization.

###########################
#       Double doors      #
###########################

# When true, players can open-close double doors with right-click.
# They need the permission "doorsreloaded.doubledoors" which is given to all players by default
allow-doubledoors: true

# Also open/close both doors when one door gets powered by redstone.
# Note: if both doors are powered and only signal gets cut, only one door will close (like in vanilla)
check-for-redstone: true

###########################
#        Iron Doors       #
###########################

# When true, players can open-close iron doors and iron trapdoors with right-click.
# They need the permission "doorsreloaded.irondoors".
allow-opening-irondoors-with-hands: false

# Automatically closes iron doors and trapdoors after the given amount of seconds (0 to disable).
autoclose: 0

###########################
#         Knocking        #
###########################

# When true, players can knock on doors using left-click.
# This only works for players in survival and adventure mode.
# They need the permission "doorsreloaded.knock" which is given to all players by default
allow-knocking: true

# When true, players can knock to trapdoors like normal doors.
# Players still need the permission "doorsreloaded.knock" which is given to all players by default
# If allow-knocking is false, this feature won't work
allow-knocking-trapdoors: false

# When true, players can only knock when their hand is empty.
knocking-requires-empty-hand: false

# When true, players can only knock while sneaking
knocking-requires-shift: false

# Settings for the knocking sound
# See here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sound-knock-iron: "minecraft:entity.zombie.attack_iron_door"
sound-knock-wood: "minecraft:item.shield.block"
# A volume of 1.0 means 16 blocks, 2.0 means 32 blocks, etc.
sound-knock-volume: 1.0
sound-knock-pitch: 1.0
# See here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/SoundCategory.html
sound-knock-category: BLOCKS

###########################
#           Misc          #
###########################

# Debug mode
debug: false